backend/config/urls.py
"""Project URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include ('accounts.urls', namespace='accounts')),
    # path('watchlater/', views.watchlater, name='watchlater'),
    path('videos/', include('videos.urls', namespace='videos')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/core/urls.py
from django.urls import path

from .views import home, tour, explore

app_name = 'core'

urlpatterns = [
    path('tour/', tour, name='tour'),
    path('explore/', explore, name='explore'),
    path('', home, name='home'),
]

backend/videos/urls.py
from django.urls import path

from . import views

app_name = 'videos'

urlpatterns = [
    path('create/', views.video_create, name='create'),
    path('<int:id>/favorite/',
		views.video_favorite,
		name='favorite'),

	path('<int:id>/unfavorite/',
		views.video_unfavorite,
		name='unfavorite'),
    path('<slug:slug>/', views.video_detail, name='detail'),
]

backend/videos/models.py
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from django.utils.translation import gettext as _

# from PIL import Image


class Category(models.Model):
    """Model representing a video category."""

    name = models.CharField(verbose_name=_('name'),
                            max_length=150,
                            db_index=True,
                            help_text=_('category name.'),
                            unique=True)
    slug = models.SlugField(verbose_name=_('slug'),
                            max_length=100,
                            unique=True)
    description = models.CharField(verbose_name=_('description'),
                                   max_length=100)
    image = models.ImageField(verbose_name=_('image'), upload_to='categories')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __str__(self):
        """String for representing the category object."""
        return self.name

    def get_absolute_url(self):
        """Return the URL to access a particular instance of category."""
        return reverse('core:category_detail', kwargs={'slug': self.slug})


class Video(models.Model):
    """Video model"""

    PRIVATE = 'PR'
    PUBLIC = 'PU'
    PRIVACY_CHOICES = [
        (PRIVATE, 'Private'),
        (PUBLIC, 'Public'),
    ]

    GENERAL = 'G'
    PARENTAL = 'PG'
    MATURED = 'M'
    RATING_CHOICES = [
        (GENERAL, 'General Audience'),
        (PARENTAL, 'Parental Guidance Suggested'),
        (MATURED, 'Mature Audience Only'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name=_('videos'),
                             verbose_name=_('user'))
    title = models.CharField(verbose_name=_('title'),
                             max_length=250,
                             db_index=True,
                             help_text=_('Title of the video.'))
    # use uuid?
    slug = models.SlugField(verbose_name=_('slug'),
                            max_length=100,
                            unique=True)
    video_file = models.FileField(verbose_name=_('Video file'),
                                  upload_to='videos',
                                  validators=[FileExtensionValidator(['mp4'])],
                                  help_text=_('Path to the uploaded video.'))
    thumbnail = models.ImageField(verbose_name=_('thumbnail'),
                                  upload_to='thumbnails',
                                  validators=[FileExtensionValidator(
                                    ['jpg', 'jpeg', 'png', 'webp'])],
                                  help_text=_('An image that will be used as a thumbnail.'))
    description = models.TextField(verbose_name=_('description'),
                                   max_length=1000,
                                   help_text=_('Description of the video.'))
    privacy = models.CharField(verbose_name=_('privacy'),
                               max_length=2,
                               choices=PRIVACY_CHOICES,
                               default=PUBLIC)
    movie_rating = models.CharField(verbose_name=_('movie rating'),
                                    max_length=2,
                                    choices=RATING_CHOICES)
    impressions = models.PositiveBigIntegerField(verbose_name=_('impressions'),
                                                 default=0,
                                                 help_text=_('View count for a video.'))
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name=_('videos'),
                                 verbose_name=_('categories'),
                                 blank=True)
    released = models.DateField(blank=True, null=True)
    enable_comments = models.BooleanField(verbose_name=_('enable comments'),
                                          default=True,
                                          help_text=_('Flag to turn on/off commenting'))
    created = models.DateTimeField(verbose_name=_('created'),
                                   auto_now_add=True,
                                   help_text=_('The date/time when the user uploaded the video'))
    updated = models.DateTimeField(verbose_name=_('updated'),
                                   auto_now=True,
                                   help_text=_('The date/time when the user made changes to the video information'))
    favorites = models.BigIntegerField(default=0)
    users_favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name=_('videos_favorites'),
                                       verbose_name=_('users favorites'),
                                       blank=True,
                                       help_text=_('Users who added video to their favorites.'))
    video_length = models.CharField(verbose_name=_('video length'),
                                    max_length=10,
                                    help_text=_('Length of the video in minutes:seconds'),
                                    blank=True)
    
    flag = models.BooleanField(verbose_name=_('_is flagged?'),
                               default=False,
                               help_text=_('If this video has been flagged for violations'))

    class Meta:
        ordering = ['-created']
        verbose_name = _('video')
        verbose_name_plural = _('videos')

    def get_absolute_url(self):
        return reverse('videos:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    # Untested code
    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     thumb = Image.open(self.thumbnail.path)

    #     if thumb.height > 300 or thumb.width > 300:
    #         output_size = (300, 300)
    #         thumb.thumbnail(output_size)
    #         thumb.save(self.thumbnail.path)

class Comment(models.Model):
    video = models.ForeignKey(
        Video,
        on_delete=models.CASCADE,
        related_name='comments')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='user_comments')
    body = models.TextField(_('body'))
    created = models.DateTimeField(
        auto_now_add=True)
    active = models.BooleanField(
        default=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.user.username} - {self.video.title}'

backend/videos/forms.py
from django import forms

from .models import Video, Comment


class VideoUploadForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Video
        fields = ['title', 'video_file', 'thumbnail', 'description', 'category']


class CommentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Comment
        fields = ['body']

backend/videos/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from core.utils import mk_paginator
from django.utils.text import slugify
from django.contrib import messages
from moviepy.editor import VideoFileClip
from .forms import VideoUploadForm, CommentForm
from django.http import HttpResponseBadRequest
from .models import Video, Category



def format_video_length(seconds):
    hours = seconds // 3600
    seconds %= 3600
    mins = seconds // 60
    seconds %= 60
    return f'{mins}:{seconds}'

@login_required
def video_create(request):
    """
    View to enable a Creator upload a video.

    Template: ``videos/video_create.html``
    Context:
        form
            Video form
    """
    if not request.user.is_creator:
        messages.success(
            request, 'Only creators are allowed to upload a video.')
        return redirect('core:home')
    
    categories = Category.objects.all()
    
    if request.method == 'POST':
        form = VideoUploadForm(request.POST, request.FILES)
        if form.is_valid():
            video = form.save(commit=False)
            video.user = request.user
            video.slug = slugify(video.title)
            
            video_file_path = request.FILES['video_file']
            clip = VideoFileClip(video_file_path.temporary_file_path())
            temporary_video_length = int(clip.duration)
            if temporary_video_length > 900:
                video_length_error = 'Your video was more than 15 minutes, upload another.'
                return render(
                    request, 'videos/video_create.html',
                    {'form':form, 'video_length_error': video_length_error})
            elif temporary_video_length <= 900:
                video.video_length = format_video_length(int(clip.duration))
                video.save()
                return redirect(video.get_absolute_url())
        else:
            messages.warning(
                request, "An error occured, check below.") 
    else:
        form = VideoUploadForm()

    template = 'videos/video_create.html'
    context = {
        'form': form,
        'categories': categories,
    }

    return render(request, template, context)


@login_required
def video_detail(request, slug):
    """
    Video detail.

    Template: ``videos/video_detail.html``
    Context:
        video
            Given video
    """

    video = get_object_or_404(Video, slug__iexact=slug)

    session_key = 'viewed_story_{}'.format(video.pk)
    if not request.session.get(session_key, False):
        video.impressions += 1
        video.save()
        request.session[session_key] = True

    similar_videos = Video.objects.filter(
        category=video.category).exclude(id=video.id)

    comments = video.comments.all()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.video = video
            comment.save()
            messages.success(
                request, "Thanks! Your comment was submitted successfully.")
            return redirect(video.get_absolute_url())
        else:
            messages.warning(
                request, "An error occured while submitting your form, check below")
    else:
        comment_form = CommentForm()


    template = 'videos/video_detail.html'
    context = {
        'video': video,
        'similar_videos': similar_videos,
        'comments': comments,
    }

    return render(request, template, context)


@login_required
def video_favorite(request, id):
    video = get_object_or_404(Video, id=id)
    current_url = request.META['HTTP_REFERER']
    users_favorites = video.users_favorites.filter(
        email=request.user.email)
    if not users_favorites:
        video.favorites += 1
        video.users_favorites.add(request.user)
        messages.success(
            request, "This video has been added to your favorites.")
        return redirect(current_url)
    else:
        return HttpResponseBadRequest()


@login_required
def video_unfavorite(request, id):
    video = get_object_or_404(Video, id=id)
    current_url = request.META['HTTP_REFERER']
    users_favorites = video.users_favorites.filter(
        email=request.user.email)
    if users_favorites:
        video.favorites -= 1
        video.users_favorites.remove(request.user)
        messages.success(
            request, "This video has been deleted from your favorites.")
        return redirect(current_url)
    else:
        return HttpResponseBadRequest()

backend/templates/videos/video_create.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/upload/views.css' %}">
    <link rel="stylesheet" href="{% static 'styles/upload/style.css' %}">
    <link rel="shortcut icon" href="{% static 'images/Group 1.png' %}" type="image/x-icon">
    <title>Vidhut</title>
</head>

<body id="body-pd">
    <header class="header container-fluid" id="header">

        <input type="search" class="search field" placeholder="Enter your search" aria-label="Search">

        <div>
            <img src="{% static 'images/user.png' %}">
        </div>
        <a href="">
            <img class="notification" src="{% static 'images/Notification.png' %}" alt="image">
        </a>

    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div>
                <div class="text-center text-white"><a href="#" class="nav_logo"><img
                            src="{% static 'images/Group 1.png' %}" alt=""></a>Home</div><br>

                <div class="nav_list"> <a href="#" class="nav_link active"> <img src="{% static 'images/Explore.png' %}"
                            alt=""></a><a href="#" class="nav_link"> <img src="{% static 'images/Vector (2).png' %}"
                            alt=""></a> <a href="#" class="nav_link"> <img src="{% static 'images/Vector (3).png' %}"
                            alt=""> </a> <a href="#" id="v-pills-tab" class="nav_link"> <img
                            src="{% static 'images/setting-2.png' %}" alt=""> </a> </div>
            </div class=""> <a href="#" class="nav_link privacy-policy">Privacy <br>Policy</a>
    </div>
    </nav>
    </div>
    <!--Container Main start-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg mt-5 mb-3">
                <div>
                    <h4>Upload</h4>
                </div>
            </div>

        </div>
        {% include 'partials/_alerts.html' %}

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'partials/_form_errors.html' %}

            {% if video_length_error %}
            <div class="alert alert-danger fade show" role="alert">
                {{video_length_error}}
            </div>
            {% endif %}

            <div class="row">
                <div class="col-lg-6">
                    <div class="upload">
                        <img src="{% static 'images/tao2.png' %}" class="bg-img" alt="taoma">
                        <input type="file" name="video_file" class="form-control" required id="id_video_file" hidden>
                        <label class="upload-btn" for="id_video_file">
                            <div class="in-line"><img src="{% static 'styles/upload/file-upload.svg' %}" alt=""></div>Select video
                        </label>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="upload">
                        <img src="https://via.placeholder.com/553x311" class="bg-img" alt="" id="output">
                        <input type="file" accept="image/*" name="thumbnail" id="id_thumbnail" hidden onchange="loadFile(event)" required>
                        <!-- <input type="file" id="upload-btn" hidden> -->
                        <label class="upload-btn" for="id_thumbnail">
                            <div class="in-line"><img src="{% static 'styles/upload/file-upload.svg' %}" alt=""></div>Select
                            thumbnail
                        </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="mt-5 field">
                        <div class="mb-3">
                            <label for="id_title" class="form-label">Video Title</label>
                            <input type="text" class="form-control label" id="id_title" name="title" maxlength="250"
                                placeholder="Enter a video title" required>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="mt-5 field">
                        <label for="id_category" class="form-label field">Select a Category</label>
                        <select class="form-select label" name="category" id="id_category" aria-label="Default">
                            <div class="select-options">
                                {% for category in categories %}
                                <option value="{{ category.pk }}">{{ category.name }}</option>
                                {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="mb-3">
                        <label for="id_description" class="form-label">Description</label>
                        <textarea name="description" class="form-control label" maxlength="1000" rows="3"
                            placeholder="Enter a short description" required id="id_description"></textarea>
                    </div>
                </div>
            </div> 
            <div class="d-flex justify-content-center mt-3">
                <button type="submit" class="button mt-5 mb-5">Upload Video</button>
            </div>
        </form>

    </div>
    <script src="{% static 'styles/upload/views.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
                crossorigin="anonymous"></script>
    <script>
        var loadFile = function (event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
        };

        document.querySelector("#file-input").addEventListener('change', function () {
            // Set object URL as the video <source>
            document.querySelector("#video-element source").setAttribute('src', URL.createObjectURL(document.querySelector("#file-input").files[0]));
        });
    </script>
</body>

</html>

backend/templates/videos/video_detail.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/watch.css' %}">
    <link rel="shortcut icon" href="{% static 'images/Group 1.png' %}" type="image/x-icon">
    <link href="https://unpkg.com/video.js@7/dist/video-js.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/@videojs/themes@1/dist/city/index.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Vidhut</title>
    <style>
        :root {
            --avatar-size: 3rem;
        }

        .circle {
            background-color: #ccc;
            border-radius: 50%;
            height: var(--avatar-size);
            text-align: center;
            width: var(--avatar-size);
        }

        .initials {
            font-size: calc(var(--avatar-size) / 2); /* 50% of parent */
            line-height: 1;
            position: relative;
            top: calc(var(--avatar-size) / 4); /* 25% of parent */
        }

    </style>
</head>
<body id="body-pd">
        
    {% include "partials/_icon_navbar.html" %}

        <!--Container Main start-->
        <div class="container col-md-12">
            <div class="main-video-container">
                {% include "partials/_alerts.html" %}
                <h4 class="video-header">By: {{ video.user }}</h4>
                <!-- <video controls id="video" class="video" preload="metadata" poster="{{ video.thumbnail.url }}">
                    <source src="{{ video.video_file.url }}" type="video/mp4">
                    </source>
                </video> -->

                <video id="my-video" class="video-js vjs-theme-city video" controls preload="auto" width="640" height="500" poster="{{ video.thumbnail.url }}"
                    data-setup="{}">
                    <source src="{{ video.video_file.url }}" type="video/mp4" />
                    <p class="vjs-no-js">
                        To view this video please enable JavaScript, and consider upgrading to a
                        web browser that
                        <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                    </p>
                </video>
                <!-- <div class="video-controls hidden" id="video-controls">
                    <button id="play_pause"><img src="Icon.png" alt=""></button>
                    <button hidden><img class="pause" src="pause.png" alt=""></button>
                    <input class="seek" id="seek" value="0" min="0" type="range" step="1">
                    <div class="seek-tooltip" id="seek-tooltip"></div>
                    <div class="time">
                        <time id="time-elapsed">00:00</time>
                        <span> / </span>
                        <time id="duration">00:00</time>
                    </div>
                    <button id="volume"><img src="volume-high.png" alt=""></button>
                    <a href="#download"><button id="download"><img src="Download.png" alt=""></button></a>
                    <a href="#share"><button id="share"><img src="send-2.png" alt=""></button></a>
                </div> -->
                <div class="video-details">
                    <div id="video-title">
                        <p>{{ video.title }}</p>
                    </div>
                    <div id="views">
                        <p>{{ video.impressions }} view{{ video.impressions|pluralize }}</p>
                    </div>
                    <div id="video-upload-date">
                        <p>{{ video.created|date:"d M Y" }}</p>
                    </div>
                    <p class="description">{{ video.description }}</p>
                    
                    {% if request.user.is_authenticated %}
                    
                        <div class="likes">
                            {% if not video.user == request.user %}
                                {% if request.user in video.users_favorites.all %}
                                    <a href="{% url 'videos:unfavorite' video.id %}" title="Unfavorite this" rel="nofollow">
                                        <span class="fa fa-heart" style="color: #21bb9d;"></span>
                                    </a>
                                {% else %}
                                    <a href="{% url 'videos:favorite' video.id %}" title="Favorite this" rel="nofollow">
                                        <span class="fa fa-heart-o"></span>
                                    </a>
                                {% endif %}
                            {% endif %}
                            <span class="ms-2">{{ video.favorites }}</span>
                        </div>
                    {% endif %}
                    <!-- <div class="follow"><a class="follow" href="#follow">Follow</a> </div> -->

                </div>

                <div class="comment-section">
                    <form action="" method="post">
                        {% csrf_token %}
                        <input class="comment" type="text" placeholder="Add a comment" name="body" required id="id_body">
                        <button type="submit" id="send"><img src="{% static 'images/send.png' %}" alt=""></button>
                    </form>
                    
                </div>

                <div class="row">
                    <div class="col-lg-6">
                        {% for comment in comments %}
                        <div class="d-flex mb-3">
                            <div class="flex-shrink-0 circle">
                                <span class="initials">{{ comment.user|make_list|first|title }}</span>
                            </div>
                            <div class="flex-grow-1 ms-3 mt-3 text-white">
                                {{ comment.body }}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
        <!--Container Main end-->
        <script src="{% static 'scripts/views.js' %}"></script>
        <script src="https://vjs.zencdn.net/7.20.1/video.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous"></script>
    </body>

</html>