backend/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = "accounts"   


urlpatterns = [
     path('logout/',
          auth_views.LogoutView.as_view(), name='logout'),
     path('login/',
          auth_views.LoginView.as_view(
               redirect_authenticated_user=True), name='login'),

     # Account activation
     path('activation/sent/',
        views.account_activation_sent,
        name='account_activation_sent'),
     path('activate/<uidb64>/<token>/',
        views.activate, 
        name='activate'),

     # password reset with email
     path('password_reset/', 
          auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
          name='password_reset'),
     path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
          name='password_reset_done'),
     path('password_reset/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
          name='password_reset_confirm'),
     path('password_reset/complete/',
          auth_views.PasswordResetCompleteView.as_view(),
          name='password_reset_complete'),

    # Registration
    path('signup/choice/', views.signup_choice, name='signup_choice'),
    path('creator/signup/', views.creator_signup, name='creator_signup'),
    path('viewer/signup/', views.viewer_signup, name='viewer_signup'),

    # Profile
    path('profile/', views.profile, name='profile'),
]

backend/config/urls.py
"""Project URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include ('accounts.urls', namespace='accounts')),
    # path('watchlater/', views.watchlater, name='watchlater'),
    path('videos/', include('videos.urls', namespace='videos')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/core/urls.py
from django.urls import path

from .views import home, tour, explore

app_name = 'core'

urlpatterns = [
    path('tour/', tour, name='tour'),
    path('explore/', explore, name='explore'),
    path('', home, name='home'),
]

backend/videos/urls.py
from django.urls import path

from . import views

app_name = 'videos'

urlpatterns = [
    path('create/', views.video_create, name='create'),
    path('<int:id>/favorite/',
		views.video_favorite,
		name='favorite'),

	path('<int:id>/unfavorite/',
		views.video_unfavorite,
		name='unfavorite'),
    path('<slug:slug>/', views.video_detail, name='detail'),
]

backend/templates/partials/_alerts.html
{% if messages %}
{% for message in messages %}

<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endfor %}
{% endif %}

backend/templates/partials/_form_errors.html
{% if form.non_field_errors %}
<div class="alert alert-warning" role="alert">
    {% for error in form.non_field_errors %}
    <p {% if forloop.last %}class="mb-0" {% endif %}>{{ error }}</p>
    {% endfor %}
</div>
{% endif %}

{% for hidden_field in form.hidden_fields %}
{% if hidden_field.errors %}
<div class="alert alert-warning" role="alert">
    {% for error in hidden_field.errors %}
    <p {% if forloop.last %}class="mb-0" {% endif %}>(Hidden field {{ hidden_field.name }}) {{ error }}</p>
    {% endfor %}
</div>
{% endif %}
{% endfor %}

backend/templates/partials/_icon_navbar.html
{% load static %}

<header class="header" id="header">
    <div class="header_toggle d-lg-none">
        <img src="{% static 'images/menu.png' %}" id="header-toggle"></img>
    </div>
    <div>
        <input type="search" class="search" placeholder="Enter your search" aria-label="Search">
    </div>
    <div>
        <a href="{% url 'accounts:profile' %}">
            <img src="{% static 'images/user.png' %}">
        </a>
        <a href="">
            <img class="notification" src="{% static 'images/Notification.png' %}" alt="image">
        </a>
        {% if request.user.is_creator %}
        <a class="btn upload" href="{% url 'videos:create' %}">
            <img src="{% static 'images/Upload.png' %}" placeholder="Upload" alt="">
        </a>
        {% endif %}
        <a class="btn upload" href="{% url 'accounts:logout' %}">Logout</a>
    </div>
</header>

<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <div class="text-center text-white">
                <a href="{% url 'core:home' %}" class="nav_logo {% url 'core:home' as home_url %}{% if request.get_full_path == home_url %}active{% endif %}">
                    <img src="{% static 'images/favicon.png' %}" alt="">
                </a> Home
            </div>
            <br>
            <div class="text-center text-white">
                <a href="{% url 'core:explore' %}" class="nav_logo {% url 'core:explore' as explore_url %}{% if request.get_full_path == explore_url %}active{% endif %}">
                    <img src="{% static 'images/Explore.png' %}" alt="">
                </a> Explore
            </div>
            <br>
            <div class="text-center text-white">
                <a href="{# url 'core:explore' #}" class="nav_logo">
                    <img src="{% static 'images/Vector (2).png' %}" alt="">
                </a> Library
            </div>
            <br>
            <div class="text-center text-white">
                <a href="{# url 'core:explore' #}" class="nav_logo">
                    <img src="{% static 'images/Vector (3).png' %}" alt="">
                </a> Huts
            </div>
            <br>
            <div class="text-center text-white">
                <a href="{# url 'core:explore' #}" class="nav_logo">
                    <img src="{% static 'images/setting-2.png' %}" alt="">
                </a> Settings
            </div>
            <br>
        </div> 
        <a href="#" class="nav_link privacy-policy">Privacy <br>Policy</a>
    </nav>
</div>

backend/templates/partials/_video_card.html
{% load static %}
{% load humanize %}

<div class="main-video-container">
    <a href="{{ video.get_absolute_url }}">
        <video class="main-video" poster="{{ video.thumbnail.url }}" src="" type="video/mp4"></video>
    </a>
    <div class="video-duration">{{ video.video_length }}</div></a>
    <!-- <div class="creator-details">
        <img class="profile-image" src="" alt="">
    </div> -->
    <h5 class="main-vid-title">{{ video.title }}</h5>
    <div class="meta-data">
        <div class="time"><img src="{% static 'images/Clock.png' %}" alt="">
            <p class="details">{{ video.created|naturaltime }}</p>
        </div>
        <div class="views"><img src="{% static 'images/eye.png' %}" alt="">
            <p class="details">{{ video.impressions }} view{{ video.impression|pluralize }}</p>
        </div>
        <div class="likes"><img src="{% static 'images/Vector.png' %}" alt="">
            <p class="details">{{ video.favorites }}</p>
        </div>
    </div>
</div>