backend/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = "accounts"   


urlpatterns = [
     path('logout/',
          auth_views.LogoutView.as_view(), name='logout'),
     path('login/',
          auth_views.LoginView.as_view(
               redirect_authenticated_user=True), name='login'),

     # Account activation
     path('activation/sent/',
        views.account_activation_sent,
        name='account_activation_sent'),
     path('activate/<uidb64>/<token>/',
        views.activate, 
        name='activate'),

     # password reset with email
     path('password_reset/', 
          auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
          name='password_reset'),
     path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
          name='password_reset_done'),
     path('password_reset/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
          name='password_reset_confirm'),
     path('password_reset/complete/',
          auth_views.PasswordResetCompleteView.as_view(),
          name='password_reset_complete'),

    # Registration
    path('signup/choice/', views.signup_choice, name='signup_choice'),
    path('creator/signup/', views.creator_signup, name='creator_signup'),
    path('viewer/signup/', views.viewer_signup, name='viewer_signup'),

    # Profile
    path('profile/', views.profile, name='profile'),
]

backend/config/urls.py
"""Project URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include ('accounts.urls', namespace='accounts')),
    # path('watchlater/', views.watchlater, name='watchlater'),
    path('videos/', include('videos.urls', namespace='videos')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/core/urls.py
from django.urls import path

from .views import home, tour, explore

app_name = 'core'

urlpatterns = [
    path('tour/', tour, name='tour'),
    path('explore/', explore, name='explore'),
    path('', home, name='home'),
]

backend/core/views.py
from django.shortcuts import render
from videos.models import Category, Video

def home(request):

    if request.user.is_authenticated:
        videos = Video.objects.all()
        categories = Category.objects.all()

        template = 'core/home.html'
        context = {'videos': videos, 'categories': categories}
        return render(request, template, context)
    else:
        categories = Category.objects.all()
        template = 'core/landing.html'
        context = {'categories': categories}
        return render(request, template, context)


def tour(request):
    videos = Video.objects.all()

    template = 'core/tour.html'
    context = {'videos': videos}
    return render(request, template, context)


def explore(request):
    videos = Video.objects.all()

    template = 'core/explore.html'
    context = {'videos': videos}
    return render(request, template, context)

backend/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/views.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    {% block styles %}{% endblock %}
    <title>{% block title %}{% endblock title %} | Vidhut</title>
</head>

<body id="body-pd">
    {% include "partials/_icon_navbar.html" %}

    <!--Container Main start-->
    <div class="container">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!--Container Main end-->
    <script src="{% static 'scripts/views.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>

</html>

backend/templates/core/explore.html
{% extends "core/base.html" %}

{% block title %}Explore{% endblock title %}

{% block content %}

{% for video in videos %}
<div class="col-md-3">
    {% include 'partials/_video_card.html' %}
</div>
{% endfor %}
{% endblock %}

backend/templates/core/home.html
{% extends "core/base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
<style>
    .vidhut__button-primary {
    background-color: #2B333A;
    margin-right: 20px;
    border-radius: 8px;
    font-weight: 600;
    padding: 8px 16px;
    font-family: Montserrat;
    color: white;
}

.vidhut__button-primary:hover {
    background-color: #BCE6AD;
    color: #000A12;
}
</style>

<div class="row mb-3">
    {% for c in categories %}
    <div class="col-lg-1 me-2">
        <a href="{# c.get_absolute_url #}" class="btn vidhut__button-primary mb-1">{{ c.name }}</a>
    </div>
    {% endfor %}
</div>


{% for video in videos %}
<div class="col-md-3">
    {% include 'partials/_video_card.html' %}
</div>
{% endfor %}
{% endblock %}

backend/templates/core/landing.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to VidHut</title>
    <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/app.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
</head>

<body>
    <!-- Header -->
    <header>
        <!-- Navbar -->
        <nav class="navbar vidhut__bg-grey navbar-expand-lg">
            <div class="container">
                <!-- Logo -->
                <a class="navbar-brand me-5" href="{% url 'core:home' %}">
                    <img src="{% static 'images/logo.png' %}" alt="VidHut">
                </a>
                <!-- Navbar Toggler -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Menu -->
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link {% url 'core:home' as home_url %}{% if request.get_full_path == home_url %}vidhut__nav-active{% else %}vidhut__text-white{% endif %} me-4" href="{% url 'core:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-4 vidhut__text-white" href="#features">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-4 vidhut__text-white" href="#howto">How To</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-4 vidhut__text-white" href="#categories">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-4 vidhut__text-white" href="#contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-4 {% url 'core:tour' as tour_url %}{% if request.get_full_path == tour_url %}vidhut__nav-active{% else %}vidhut__text-white{% endif %}" href="{% url 'core:tour' %}">Tour hut</a>
                        </li>
                    </ul>
                    <div class="navbar-nav ms-auto">
                        <a href="{% url 'accounts:signup_choice' %}" class="btn vidhut__button-primary mb-1">Sign up</a>
                        <a href="{% url 'accounts:login' %}" class="btn vidhut__button-secondary mb-1 me-lg-0">Log in</a>
                    </div>
                </div>
            </div>
        </nav> <!-- End Navbar -->

        <!-- Hero -->
        <div class="container hero">
            <div class="row justify-content-center">
                <div class="col-md-12 text-center">
                    <h1 class="mb-5">Find amazing entertainment in your hut now!</h1>
                </div>
                <div class="col-md-8 text-center">
                    <h4 class="mb-5">You are just a click away from uploading, viewing and sharing films with students
                        just like you</h4>
                    <a class="btn vidhut__button-primary fs-5" href="{% url 'accounts:signup_choice' %}">Join hut</a>
                </div>
            </div>
        </div> <!-- End Hero -->
    </header>

    <!-- Features -->
    <section class="vidhut__bg-dark" id="features">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-title">Our amazing features</h2>
                    <p class="section-description">Your needs and wants are our prioirity. Stay entertained always with
                        our magnificent features that gives you the best and most unique experience you can ever get on
                        a streaming platform.</p>
                </div>
            </div>

            <div class="feature-row">
                <div class="row">
                    <div class="col-md-6 me-5">
                        <img class="img-fluid" src="{% static 'images/feature-1.jpg' %}" alt="">
                    </div>
                    <div class="col-md-5 pt-5">
                        <h3>Love to create contents</h3>
                        <p>Upload your videos and reach a wide range of audience consisting of college students and the
                            rest of the world.</p>
                    </div>
                </div>
            </div>

            <div class="feature-row">
                <div class="row">
                    <div class="col-md-5 pt-5">
                        <h3>Stream and download</h3>
                        <p>The entertainment never stops. With data turned on or off, watch and download amazing content
                            in your hut.</p>
                    </div>
                    <div class="col-md-6 ms-5">
                        <img class="img-fluid" src="{% static 'images/feature-2.jpg' %}" alt="">
                    </div>
                </div>
            </div>

            <div class="feature-row">
                <div class="row">
                    <div class="col-md-6 me-5">
                        <img class="img-fluid" src="{% static 'images/feature-3.jpg' %}" alt="">
                    </div>
                    <div class="col-md-5 pt-5">
                        <h3>Join a community</h3>
                        <p>Want to bant and interact with your fellow content creator and college students? We have just
                            the hut for you.</p>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <!--How to upload-->
    <section class="vidhut__bg-grey" id="howto">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-title">How to upload</h2>
                    <p class="section-description">Are you a creator in university? Do you have videos to share to your
                        university folks and the rest of the world. Upload a video on Vidhut in 5 easy steps.</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 d-flex justify-content-between">
                    <div class="badge rounded-pill">
                        <h5>1</h5>
                    </div>
                    <div class="col howtoupload">
                        <img class="img-fluid mb-3" src="{% static 'images/how-to-1.jpg' %}" alt="Create account">
                        <p class="text-center">Create account</p>
                    </div>
                    <div class="badge rounded-pill">
                        <h5>2</h5>
                    </div>
                    <div class="col howtoupload">
                        <img class="img-fluid mb-3" src="{% static 'images/how-to-2.jpg' %}" alt="Choose niche">
                        <p class="text-center">Choose niche</p>
                    </div>
                    <div class="badge rounded-pill">
                        <h5>3</h5>
                    </div>
                    <div class="col howtoupload me-0">
                        <img class="img-fluid mb-3" src="{% static 'images/how-to-3.jpg' %}" alt="">
                        <p class="text-center">Verify Email</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-9 d-flex justify-content-center offset-lg-2">
                    <div class="badge rounded-pill">
                        <h5>4</h5>
                    </div>
                    <div class="col howtoupload">
                        <img class="img-fluid mb-3" src="{% static 'images/how-to-4.jpg' %}" alt="Scan school ID card">
                        <p class="text-center">Scan school ID card</p>
                    </div>
                    <div class="badge rounded-pill">
                        <h5>5</h5>
                    </div>
                    <div class="col howtoupload">
                        <img class="img-fluid mb-3" src="{% static 'images/how-to-5.jpg' %}" alt="Upload video">
                        <p class="text-center">Upload video</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Categories -->
    <section class="vidhut__bg-dark" id="categories">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-title">Tour diverse categories</h2>
                    <p class="section-description">At Vidhut, we offer you various categories to browse videos from,
                        tour and find your hut.</p>
                </div>
            </div>

            <div class="row justify-content-center">
                {% for c in categories %}
                <div class="col-md-3 card p-4">
                    <img class="img-fluid mb-3" src="{{ c.image.url }}" alt="">
                    <h4><a href="{# c.get_absolute_url #}" class="text-decoration-none text-white">{{ c.name }}</a></h4>
                    <p class="card-text">{{ c.description }}</p>
                </div>
                {% endfor %}
                <a class="mt-4 btn see-more" href="javascript:void(0)">More categories</a>
            </div>
        </div>
    </section>

    <!-- Contact -->
    <section class="vidhut__bg-grey" id="contact">
        <div class="container">
            <div class="row mb-5">
                <div class="col-lg-12 text-center">
                    <h3 class="section-title">Contact Customer Service</h3>
                    <p class="section-description">Need help, clarification or anything in-between?</p>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-3 vidhut__bg-dark vidhut__rounded-border p-5 mx-5 mb-3">
                    <img src="{% static 'images/call.png' %}" alt="Call us">
                    <h4 class="ms-3 d-inline">Call us</h4>
                    <p class="mt-3 mb-0 fs-5">+234 701 4300 630</p>
                    <p class="fs-5">+234 701 2345 689</p>
                </div>
                <div class="col-md-3 vidhut__bg-dark vidhut__rounded-border p-5 mx-5 mb-3">
                    <img src="{% static 'images/call.png' %}" alt="chatlive">
                    <h4 class="ms-3 d-inline">Chat live</h4>
                    <p class="mt-3 fs-5">We're available <br>
                        8am-8pm <br>Monday-Saturday</p>
                </div>
                <div class="col-md-3 vidhut__bg-dark vidhut__rounded-border p-5 mx-5 mb-3">
                    <img src="{% static 'images/call.png' %}" alt="visitus">
                    <h4 class="ms-3 d-inline">Visit us</h4>
                    <p class="mt-3 fs-5">
                        18 Tolu Crescent <br>
                        off Mali street, <br>
                        Emmanuella Ave.</p>
                </div>
            </div>
        </div>
    </section>

    <footer class="vidhut__bg-dark">
        <div class="container py-4 px-4">
            <div class="row">
                <div class="col-lg-6 col-md col-sm col-12 mb-5">
                    <img src="{% static 'images/logo.png' %}" alt="logo">
                    <h4 class="ms-3 d-inline vidhut__text-white">Vidhut Inc. 2022</h4>
                </div>
                <div class="col-lg-2 col-md col-sm-4 col-12">
                    <h5 class="vidhut__text-white fw-bold mb-4">Explore</h5>
                    <ul class="list-unstyled">
                        <li><a href="#features">Features</a></li>
                        <li><a href="FAQs">FAQs</a></li>
                        <li><a href="#only">Only on Vidhut</a></li>
                        <li><a href="#explore">Explore contents</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md col-sm-4 col-12">
                    <h5 class="vidhut__text-white fw-bold mb-4">Company</h5>
                    <ul class="list-unstyled">
                        <li><a href="#about">About</a></li>
                        <li><a href="#privacy">Privacy</a></li>
                        <li><a href="#terms">Terms of use</a></li>
                        <li><a href="Howto">How to upload</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md col-sm-4 col-12">
                    <h5 class="vidhut__text-white fw-bold mb-4">Resources</h5>
                    <ul class="list-unstyled">
                        <li><a href="#blog">Blog</a></li>
                        <li><a href="#contact">Contact us</a></li>
                        <li><a href="#community">Community</a></li>
                        <li><a href="#mediacenter">Media center</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'scripts/app.js' %}"></script>
</body>

</html>

backend/templates/core/tour.html
{% load static %}
<!doctype html>
<html lang="en">
{% load humanize %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tour VidHut</title>
    <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/app.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar vidhut__bg-grey navbar-expand-lg">
        <div class="container">
            <!-- Logo -->
            <a class="navbar-brand me-5" href="{% url 'core:home' %}">
                <img src="{% static 'images/logo.png' %}" alt="VidHut">
            </a>
            <!-- Navbar Toggler -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Menu -->
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link {% url 'core:home' as home_url %}{% if request.get_full_path == home_url %}vidhut__nav-active{% else %}vidhut__text-white{% endif %} me-4"
                            href="{% url 'core:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link me-4 vidhut__text-white" href="#features">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link me-4 vidhut__text-white" href="#howto">How To</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link me-4 vidhut__text-white" href="#categories">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link me-4 vidhut__text-white" href="#contact">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link me-4 {% url 'core:tour' as tour_url %}{% if request.get_full_path == tour_url %}vidhut__nav-active{% else %}vidhut__text-white{% endif %}"
                            href="{% url 'core:tour' %}">Tour hut</a>
                    </li>
                </ul>
                <div class="navbar-nav ms-auto">
                    <a href="{% url 'accounts:signup_choice' %}" class="btn vidhut__button-primary mb-1">Sign up</a>
                    <a href="{% url 'accounts:login' %}" class="btn vidhut__button-secondary mb-1 me-lg-0">Log
                        in</a>
                </div>
            </div>
        </div>
    </nav> <!-- End Navbar -->

    <!-- Categories -->
    <section class="vidhut__bg-dark" id="categories">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="section-title">Trending Videos</h2>
                </div>
            </div>

            <div class="row">

                {% for video in videos %}
                <div class="col-md-3">
                    {% include 'partials/_video_card.html' %}
                </div>
                {% endfor %}
                
                <!-- <a class="mt-4 btn see-more" href="javascript:void(0)">Load More</a> -->
            </div>
        </div>
    </section>

    <footer class="vidhut__bg-grey">
        <div class="container py-4 px-4">
            <div class="row">
                <div class="col-lg-6 col-md col-sm col-12 mb-5">
                    <img src="{% static 'images/logo.png' %}" alt="logo">
                    <h4 class="ms-3 d-inline vidhut__text-white">Vidhut Inc. 2022</h4>
                </div>
                <div class="col-lg-2 col-md col-sm-4 col-12">
                    <h5 class="vidhut__text-white fw-bold mb-4">Explore</h5>
                    <ul class="list-unstyled">
                        <li><a href="#features">Features</a></li>
                        <li><a href="FAQs">FAQs</a></li>
                        <li><a href="#only">Only on Vidhut</a></li>
                        <li><a href="#explore">Explore contents</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md col-sm-4 col-12">
                    <h5 class="vidhut__text-white fw-bold mb-4">Company</h5>
                    <ul class="list-unstyled">
                        <li><a href="#about">About</a></li>
                        <li><a href="#privacy">Privacy</a></li>
                        <li><a href="#terms">Terms of use</a></li>
                        <li><a href="Howto">How to upload</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md col-sm-4 col-12">
                    <h5 class="vidhut__text-white fw-bold mb-4">Resources</h5>
                    <ul class="list-unstyled">
                        <li><a href="#blog">Blog</a></li>
                        <li><a href="#contact">Contact us</a></li>
                        <li><a href="#community">Community</a></li>
                        <li><a href="#mediacenter">Media center</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'scripts/app.js' %}"></script>
</body>

</html>